@startuml UML

set namespaceSeparator ::

interface rsc::IMovable2{
    + {abstract} move( v : Vect2f& ): void
    + {abstract} moveTo( v : Vect2f& ): void
}

interface rsc::IMovable3{
    + {abstract} move( v : Vect3f& ): void
    + {abstract} moveTo( v : Vect3f& ): void
}

class rsc::Vector2<template<typename T>> {
    + x : T
    + y : T 

    + Vector2()
    + Vector2( aX : T&, aY : T&)
    + Vector2( v : Vector2<T>)
    + ~Vector2()

    + operator=( v : Vector2<T>& ): Vector2<T>&
    + operator==( v : Vector2<T>& ): bool
    + operator!=( v : Vector2<T>& ): bool
    + operator<( v : Vector2<T>& ): bool
    + operator<=( v : Vector2<T>& ): bool
    + operator>( v : Vector2<T>& ): bool
    + operator>=( v : Vector2<T>& ): bool

    + operator+=( v : Vector2<T>& ): Vector2<T>&
    + operator-=( v : Vector2<T>& ): Vector2<T>&
    + operator+( v : Vector2<T>& ): Vector2<T>
    + operator-( v : Vector2<T>& ): Vector2<T>
    + operator*( v : Vector2<T>& ): T
    + operator*( t : T ): Vector2<T>

    + operator<<( ofs : ostream&, v : Vector2<T>& ): ostream&
    + operator>>( ifs : istream&, v : Vector2<T>& ): istream&
}

class rsc::Vector3<template<typename T>> {
    + x : T
    + y : T 
    + z : T

    + Vector3()
    + Vector3( aX : T&, aY : T&)
    + Vector3( v : Vector3<T>)
    + ~Vector3()

    + operator=( v : Vector3<T>& ): Vector3<T>&
    + operator==( v : Vector3<T>& ): bool
    + operator!=( v : Vector3<T>& ): bool
    + operator<( v : Vector3<T>& ): bool
    + operator<=( v : Vector3<T>& ): bool
    + operator>( v : Vector3<T>& ): bool
    + operator>=( v : Vector3<T>& ): bool

    + operator+=( v : Vector3<T>& ): Vector3<T>&
    + operator-=( v : Vector3<T>& ): Vector3<T>&
    + operator+( v : Vector3<T>& ): Vector3<T>
    + operator-( v : Vector3<T>& ): Vector3<T>
    + operator*( v : Vector3<T>& ): T
    + operator*( t : T ): Vector3<T>

    + operator<<( ofs : ostream&, v : Vector3<T>& ): ostream&
    + operator>>( ifs : istream&, v : Vector2<T>& ): istream&
}


class rsc::Card
{
    # value : float

    + Card()
    + Card( aV : float )
    + Card( c : Card& )
    + ~Card()

    + operator=( c : Card&): Card&
    
    + getValue(): float
}

class rsc::Deck{
    # size : size_t
    # pile : list<shared_ptr<Card>>

    + Deck()
    + Deck( d : Deck& )
    + ~Deck()

    + operator=( d : Deck& ): Deck&
    + operator[]( i : size_t ): shared_ptr<Card>&

    + getSize(): int

    + add( c : shared_ptr<Card>, loc : int ): void
    + pick_up(): shared_ptr<Card>
    + give_to( i : size_t, d : Deck&, loc : int): void
    + shuffle(): void
}

class rsc::Player{
    # name : string
    # id : int
    
    + Player( n : string )
    + Player( n : string, aId : int )
    + ~Player()

    + operator=( p : Player&): Player&

    + getName(): string&
    + getId(): int&

    + login(): void
    + logout(): void
}

class rsc::Pawn2{
    # position : Vect2f

    + Pawn2()
    + Pawn2( pos : Vect2f& )
    + Pawn2( aX : float, aY : float )
    + ~Pawn2()

    + operator=( p : Pawn2& ): Pawn2&

    + getPosition(): Vect2f&

    + move( v : Vect2f& ): void
    + moveTo( v : Vect2f& ): void
}

class rsc::Pawn3{
    # position : Vect3f

    + Pawn3()
    + Pawn3( pos : Vect2f& )
    + Pawn3( aX : float, aY : float, aZ : float )
    + ~Pawn3()

    + operator=( p : Pawn3& ): Pawn3&

    + getPosition(): Vect3f&

    + move( v : Vect3f& ): void
    + moveTo( v : Vect3f& ): void
}

class rsc::Game{
    + state : int
    + deck : Deck
    + discard : Deck
    + player : vector<Player*>

    + Game()
    + ~Game()

    + operator=( g : Game& ): Game&
    + operator[]( i : size_t ): Player*

    + setState( s : int ): void
}

rsc::IMovable2 <|-- rsc::Pawn2
rsc::IMovable3 <|-- rsc::Pawn3

rsc::Deck "1" *-- "0..n" rsc::Card

rsc::Game "4" *-- "1" rsc::Player
rsc::Game "2" *-- "1" rsc::Deck

@enduml